
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: P1809F7CD0C7575E0
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    basicAuth: false

