apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://hr-app-prometheus.nicemushroom-89003adf.canadacentral.azurecontainerapps.io
    isDefault: true
    version: 1
    editable: true

